#!/usr/bin/env bash
####

Espy=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )/..

############# assert dirs exist
mkdir -p $Espy/opt
mkdir -p $Espy/docs

chmod +x $Espy/opt/ional
chmod +x $Espy/eg.py
chmod +x $Espy/es.py

############# ensure files exist
f=opt/tmux-conf; [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=opt/vimrc;     [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=opt/pics;      [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=opt/gitignore; [ -f "$Espy/$f"  ] || wget -q -O $Espy/$f $web/$f
f=gitignore;     [ -f "$Espy/.$f" ] || cp $Espy/opt/$f $Espy/.$f

git add $Espy/opt/* $Espy/.gitignore

############## aliases
alias gp="git add *; git commit -am saving; git push; git status"
alias ls="ls -G"
alias repl="rlwrap sbcl --noinform "
alias tmux="$(which tmux) -f $Espy/opt/tmux-conf "
alias vi="vim -u $Espy/opt/vimrc "
alias vims="vim +PluginInstall +qall"         

html() {
  pdoc3 --config sort_identifiers=False        \
        --config show_inherited_members=False   \
        --force --template-dir $Espy/docs --html \
        -o $Espy/docs $Espy/*.py
  git add $Espy/docs/*.html
}

here() { cd $1; basename `pwd`; }

hi() {
  clear
  tput bold; tput setaf 32; cat <<-'EOF'
  oO)-.                       .-(Oo
 /__  _\                     /_  __\
 \  \(  |     ()~()         |  )/  /
  \__|\ |    (-___-)        | /|__/
  '  '--'    ==`-'==        '--'  '

EOF
  tput sgr0
  tput bold; tput setaf 0
  awk '/^alias/ {print $0}'   $Espy/opt/ional
  echo ""
  tput sgr0
}

mytmux() {
  session=$RANDOM
  Tmux=$(which tmux)
  $Tmux start-server
  sleep 1
  $Tmux new-session -d -s $session  
  $Tmux send-keys ". $Espy/opt/ional"  C-m  "sleep 0.5; clear; vi keys.lisp" C-m

  $Tmux splitw -h -p 20
  $Tmux selectp -t 1
  $Tmux send-keys ".  $Espy/opt/ional"  C-m  "clear; hi" C-m

  $Tmux splitw -v  -p 5
  $Tmux selectp -t 2
  $Tmux send-keys ".  $Espy/opt/ional"  C-m  "htop"  C-m

  $Tmux attach-session -t $session
}

startup() {
  if [ ! -d "$HOME/.vim/bundle" ]; then
     git clone https://github.com/VundleVim/Vundle.vim.git \
           ~/.vim/bundle/Vundle.vim
     vims
  fi
  [ -z "$TMUX" ] && mytmux
}
############### prompt
PROMPT_COMMAND='echo -ne "🧩 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

[[ $1 == "-s" ]] && startup


