export const TEST_RANGE = {
   "optimize":{
      "r1":{
         "before":[
            0.21,
            1.35,
            1.72,
            0.73
         ],
         "effect":[
            0.16,
            1.31,
            1.74,
            0.62
         ],
         "rule":[
            [
               "cruise_speed",
               3,
               [
                  [
                     50,
                     126
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               3,
               27
            ],
            "cruise_speed":[
               50,
               126
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r2":{
         "before":[
            0.37,
            0.6,
            0.6,
            0.26
         ],
         "effect":[
            0.51,
            0.29,
            0.36,
            0.16
         ],
         "rule":[
            [
               "cruise_altitude",
               5,
               [
                  [
                     173,
                     1000
                  ]
               ]
            ],
            [
               "direction",
               8,
               [
                  [
                     64,
                     180
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               3,
               27
            ],
            "cruise_speed":[
               50,
               126
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               173,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               64,
               180
            ]
         }
      },
      "r3":{
         "before":[
            0.47,
            0.22,
            0.26,
            0.07
         ],
         "effect":[
            0.48,
            0.15,
            0.13,
            0.01
         ],
         "rule":[
            [
               "cruise_altitude",
               5,
               [
                  [
                     313,
                     1000
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               3,
               27
            ],
            "cruise_speed":[
               50,
               126
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               313,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               64,
               180
            ]
         }
      },
      "r_extra":{
         "ascend_angle":[
            5,
            23
         ],
         "descend_angle_1":[
            6,
            22
         ],
         "descend_angle_2":[
            3,
            19
         ],
         "cruise_speed":[
            50,
            126
         ],
         "trip_distance":[
            11001,
            29501
         ],
         "cruise_altitude":[
            313,
            1000
         ],
         "payload":[
            0,
            1501
         ],
         "wind":[
            0,
            21
         ],
         "direction":[
            64,
            180
         ]
      }
   },
   "monitor":{
      "r1":{
         "before":[
            0.21,
            1.35,
            1.72,
            0.73
         ],
         "effect":[
            0.1,
            2.28,
            2.74,
            1.35
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r2":{
         "before":[
            0.22,
            1.33,
            1.71,
            0.71
         ],
         "effect":[
            0.1,
            2.25,
            2.72,
            1.33
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r3":{
         "before":[
            0.21,
            1.34,
            1.71,
            0.72
         ],
         "effect":[
            0.09,
            2.28,
            2.75,
            1.35
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r4":{
         "before":[
            0.21,
            1.33,
            1.7,
            0.71
         ],
         "effect":[
            0.1,
            2.28,
            2.73,
            1.35
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r5":{
         "before":[
            0.22,
            1.34,
            1.71,
            0.72
         ],
         "effect":[
            0.1,
            2.28,
            2.74,
            1.34
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r6":{
         "before":[
            0.21,
            1.37,
            1.74,
            0.74
         ],
         "effect":[
            0.09,
            2.29,
            2.75,
            1.36
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r7":{
         "before":[
            0.22,
            1.36,
            1.73,
            0.73
         ],
         "effect":[
            0.1,
            2.27,
            2.74,
            1.34
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r8":{
         "before":[
            0.22,
            1.35,
            1.73,
            0.73
         ],
         "effect":[
            0.1,
            2.29,
            2.75,
            1.36
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     9,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               9,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r9":{
         "before":[
            0.22,
            1.34,
            1.73,
            0.72
         ],
         "effect":[
            0.09,
            2.42,
            2.79,
            1.54
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     15,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               15,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r10":{
         "before":[
            0.21,
            1.34,
            1.72,
            0.72
         ],
         "effect":[
            0.08,
            2.43,
            2.79,
            1.55
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     15,
                     27
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               30
            ],
            "descend_angle_2":[
               15,
               27
            ],
            "cruise_speed":[
               50,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r_extra":{
         "ascend_angle":[
            5,
            18
         ],
         "descend_angle_1":[
            6,
            18
         ],
         "descend_angle_2":[
            15,
            27
         ],
         "cruise_speed":[
            50,
            171
         ],
         "trip_distance":[
            14001,
            29501
         ],
         "cruise_altitude":[
            551,
            951
         ],
         "payload":[
            101,
            1501
         ],
         "wind":[
            0,
            15
         ],
         "direction":[
            81,
            171
         ]
      }
   },
   "safety":{
      "r1":{
         "before":[
            0.21,
            1.35,
            1.72,
            0.73
         ],
         "effect":[
            0.23,
            0.51,
            1.16,
            0.28
         ],
         "rule":[
            [
               "descend_angle_2",
               2,
               [
                  [
                     3,
                     9
                  ]
               ]
            ],
            [
               "descend_angle_1",
               1,
               [
                  [
                     6,
                     12
                  ]
               ]
            ],
            [
               "cruise_speed",
               3,
               [
                  [
                     202,
                     300
                  ]
               ]
            ]
         ],
         "config":{
            "ascend_angle":[
               3,
               30
            ],
            "descend_angle_1":[
               6,
               12
            ],
            "descend_angle_2":[
               3,
               9
            ],
            "cruise_speed":[
               202,
               300
            ],
            "trip_distance":[
               5000,
               30000
            ],
            "cruise_altitude":[
               100,
               1000
            ],
            "payload":[
               0,
               2000
            ],
            "wind":[
               0,
               30
            ],
            "direction":[
               0,
               180
            ]
         }
      },
      "r_extra":{
         "ascend_angle":[
            5,
            14
         ],
         "descend_angle_1":[
            6,
            12
         ],
         "descend_angle_2":[
            3,
            9
         ],
         "cruise_speed":[
            202,
            300
         ],
         "trip_distance":[
            14001,
            29501
         ],
         "cruise_altitude":[
            701,
            951
         ],
         "payload":[
            101,
            1501
         ],
         "wind":[
            0,
            9
         ],
         "direction":[
            81,
            131
         ]
      }
   }
}