variables:
    - x1:
        name: Ascend_angle
        min_value: 3
        max_value: 30
    - x2:
        name: Descend_angle_1
        min_value: 6
        max_value: 30
    - x3:
        name: Descend_angle_2
        min_value: 3
        max_value: 27
    - x4:
        name: Cruise_speed
        min_value: 25
        max_value: 300
    - x5:
        name: Trip_distance
        min_value: 5000
        max_value: 30000
    - x6:
        name: Cruise_altitude
        min_value: 200
        max_value: 1000
    - x7:
        name: Payload
        min_value: 0
        max_value: 2000
    - x8:
        name: Wind
        min_value: 0
        max_value: 30
    - x9:
        name: Direction
        min_value: 0
        max_value: 180

products:
    - y1:
        name: taxi
        rules:
            - r1:
                name: t
                min_value: 0
                max_value: 0
                value: 0
            - r2:
                name: long_accel
                min_value: 1
                max_value: 1
                value: 1
            - r3:
                name: lat_accel
                min_value: 1
                max_value: 1
                value: 1
            - r4:
                name: jerk
                min_value: 0.3
                max_value: 0.3
                value: 0.3
            - r5:
                name: charging
                min_value: 0.2
                max_value: 0.2
                value: 0.2
    - y2:
        name: package
        rules:
            - r1:
                name: t
                min_value: 0
                max_value: 0
                value: 0
            - r2:
                name: long_accel
                min_value: 1
                max_value: 1
                value: 1
            - r3:
                name: lat_accel
                min_value: 1
                max_value: 1
                value: 1
            - r4:
                name: jerk
                min_value: 0.3
                max_value: 0.3
                value: 0.3
            - r5:
                name: charging
                min_value: 0.2
                max_value: 0.2
                value: 0.2
    - y3:
        name: scout
        rules:
            - r1:
                name: t
                min_value: 0
                max_value: 0
                value: 0
            - r2:
                name: long_accel
                min_value: 1
                max_value: 1
                value: 1
            - r3:
                name: lat_accel
                min_value: 1
                max_value: 1
                value: 1
            - r4:
                name: jerk
                min_value: 0.3
                max_value: 0.3
                value: 0.3
            - r5:
                name: charging
                min_value: 0.2
                max_value: 0.2
                value: 0.2

control:
    - c1:
        name: vehicle_type
        value: taxi
    - c2:
        name: generations
        min_value: 1
        max_value: 10
        value: 10
    - c3:
        name: samples
        min_value: 1000
        max_value: 100000
        value: 5000
    - c4:
        name: seed
        min_value: 1
        max_value: 100013
        value: 1

hall:
    elite:   2 # 2-7
    act:     1 # 1=optimizer, 2= monitor, 3=safety
    yround:  2 # 1,2,3
    cohen:  .3  # a boring range has a range less than cohen*sd 0-1
    size:   .5  # initial split sizes: len(simualtionResults)**size. a.k.a. square root 0-1
    k:       1  # low frequency on classes (the priors) e1*e2*e3*prior
    m:       2  # low frequency on evidence (the evidence counts e)
    top:    10
    show:   10
    minSupport: .4
  


