variables:
    - x1:
        name: Ascend_angle
        min_value: 3
        max_value: 30
    - x2:
        name: Descend_angle_1
        min_value: 6
        max_value: 30
    - x3:
        name: Descend_angle_2
        min_value: 3
        max_value: 27
    - x4:
        name: Cruise_speed
        min_value: 25
        max_value: 300
    - x5:
        name: Trip_distance
        min_value: 5000
        max_value: 30000
    - x6:
        name: Cruise_altitude
        min_value: 200
        max_value: 1000
    - x7:
        name: Payload
        min_value: 0
        max_value: 2000
    - x8:
        name: Wind
        min_value: 0
        max_value: 30
    - x9:
        name: Direction
        min_value: 0
        max_value: 180

products:
    - y1:
       name: taxi
       rules:
          t: 0
          long_accel: 1
          lat_accel: 1
          jerk: 0.3
          charging: 0.2
    - y2:
        name: package
        rules:
         t: 0
    - y3:
        name: scout
        rules:
          t: 0

control:
    vehicle_type: taxi
    generations: 10
    samples: 2000
    seed: 1

hall:
  elite:   2
  act:     1 # 1=optimizer, 2= monitor, 3=safety
  yround:  2
  cohen:  .3  # a boring range has a range less than cohen*sd
  size:   .5  # initial split sizes: len(simualtionResults)**size. a.k.a. square root
  k:       1  # low frequency on classes (the priors) e1*e2*e3*prior
  m:       2  # low frequency on evidence (the evidence counts e) 
  top:    10
  show:   10
  minSupport: .4
  


